---
title: "Week 3 PPA"
author: "RVM"
date: "2024-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
if (!require(pacman)){install.packages("pacman"); library(pacman)}
p_load (sf, tidyverse, knitr, kableExtra, rmarkdown, tidycensus, dplyr, scales)


options(scipen=999)
options(tigris_class = "sf")

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

```{r}
census_api_key("b3eda1fa84dde3c5ad443fd407d48f2584ab2726", overwrite = TRUE)

tracts09 <-  
  get_acs(geography = "tract",
          variables = c("B25026_001E","B02001_002E",
                        "B15001_050E","B15001_009E",
                        "B19013_001E", "B25058_001E",
                        "B06012_002E"), 
          year=2009, state= 34, #New Jersey FIPS code is 34, Mercer County FIPS code is 021
          county=021, geometry=TRUE) %>%
  st_transform('ESRI:102728')
```
```{r}
A1 <- 
  ggplot()+
  geom_sf(data = totalPop16, aes(fill = estimate)) +
  scale_fill_distiller(palette = "RdPu",
                       direction = 1) +
  labs(title = "2016 Population Estimates, Mercer County, New Jersey",
       caption = "Data source: 2016 3-year ACS, US Census Bureau",
       fill = "ACS estimate") +
  theme_void()

A2 <-
  ggplot() +
  geom_sf(data=totalPop16, aes(fill = estimate)) +
  scale_fill_distiller(palette = "RdPu", direction = 1,
                       breaks = pretty_breaks()) +
  labs(title = "2016 Population Estimates, Mercer County, New Jersey",
       caption = "Data source: 2016 3-year ACS, US Census Bureau",
       fill = "ACS estimate") +
  theme_void()
```


```{r}
tracts09 <- tracts09 %>%
  dplyr::select(-NAME, -moe) %>%
  spread(key = variable, value = estimate) %>%
  rename(totalPop = B25026_001, 
         whites = B02001_002,
         femaleBachelors = B15001_050, 
         maleBachelors = B15001_009,
         medHHInc = B19013_001, 
         medRent = B25058_001,
         totalPoverty = B06012_002)

tracts09 <-
  tracts09 %>%
  mutate(pctWhite = ifelse(totalPop > 0, whites/totalPop, 0),
         pctBachelors = ifelse(totalPop > 0, ((femaleBachelors + maleBachelors)/totalPop), 0),
         pctPoverty = ifelse(totalPop > 0, totalPoverty /totalPop, 0),
         year = "2009") %>%
  dplyr::select(-whites, -femaleBachelors, -maleBachelors, totalPoverty)
```

```{r results = 'hide'}
tracts17 <-
  get_acs(geography = "tract",
          variables = c("B25026_001E","B02001_002E",
                        "B15001_050E","B15001_009E",
                        "B19013_001E","B25058_001E",
                        "B06012_002E"),
          year = 2017, state = 34, county = 021,
          geometry = TRUE, output = "wide") %>%
  st_transform('ESRI:102728') %>%
  rename(totalPop = B25026_001E, 
         whites = B02001_002E,
         femaleBachelors = B15001_050E, 
         maleBachelors = B15001_009E,
         medHHInc = B19013_001E, 
         medRent = B25058_001E,
         totalPoverty = B06012_002E) %>%
  dplyr::select(-NAME, -starts_with("B")) %>%
  mutate(pctWhite = ifelse(totalPop > 0, whites/totalPop, 0),
         pctBachelors = ifelse(totalPop > 0, ((femaleBachelors + maleBachelors)/totalPop), 0),
         pctPoverty = ifelse(totalPop > 0, totalPoverty /totalPop, 0),
         year = "2017") %>%
  dplyr::select(-whites, -femaleBachelors, -maleBachelors, totalPoverty)
```
```{r}
allTracts <- rbind(tracts16, tracts20)
```

```{r}
njBus <- st_read("Bus_Stops_of_NJ_Transit_by_Line.geojson")

njBusStops <- 
     njBus %>% 
      mutate(County = "Mercer") %>%
      dplyr::select(DESCRIPTION_BSL, LINE)%>%
  st_transform(st_crs(tracts16))  

```

```{r}
ggplot() + 
  geom_sf(data=st_union(tracts16)) + #we did this to get rid of the borders of the census tracts to simplify the map. This highlights the subway stops
  geom_sf(data=njBusStops, 
          aes(colour = LINE), 
          show.legend = "point", size= 2) +
  labs(title="NJ Bus Stops", 
       subtitle="Mercer, NJ", 
       caption="Figure 2.5") +
  theme_void()
```

```{r}
stopBuffer <- st_buffer(njBusStops, 2640)

stopUnion <- st_union(st_buffer(njBusStops, 2640))

njStopBuffers <- 
  rbind(
     stopBuffer %>%
      mutate(Legend = "Buffer") %>%
      dplyr::select(Legend),
     stopUnion %>%
      st_sf() %>%
      mutate(Legend = "Unioned Buffer"))

```

```{r}
ggplot() +
  geom_sf(data=njStopBuffers) +
  geom_sf(data=njBusStops, show.legend = "point") +
  facet_wrap(~Legend) + 
  labs(caption = "Figure 2.6") +
  theme_void()
```
```{r}


```






